* Notes
  These notes are for me only, and I do not promise to
  keep them up-to-date or even accurate.
  
  The official docs are in the README.org.

** Basic design
   + We shall have, instead of negative weights,
     negative or inhibitory neurons, which will send
     the weights as negative to the neuros its conneted
     to.
   + Instead of averaging, we will use spikes. There
     are the time instants, and for each time instant
     the inputs (and their weights) for each neuron
     will be tallied, and if it reaches firing
     threshold, said neuron will fire its own pulse.
   + Some neurons will continually fire pulses at
     regular intervals. This will serve as a bias.

     I actually think there should be a number of bias
     neurons firing at regular intervals. The firing
     rates should not necessairily be random,
     either. Maybe Fibonancii? Maybe these rates
     themselves should be evolved?
   + In the Stanley algorithm, the neurons and genes
     are indexed by integers. To promote efficient
     execution of these neurons, should we maintain
     that? Perhaps we should simply create the IR from
     the indicies directly.
** Sequence Numbers and Innovation Numbers
   Innovation numbers are used to trace this history of
   evolution.  They are not intended to be IDs.

   Sequence Numbers may be used as IDs. More thought 
   is needed on this matter.
** Weights
   All weights are between 0 and 1. If the node is inhibitory
   then during the espression of the critter, the signs of
   weights are flipped.
