* Notes       :TOC_5_gh:
  - [[#about-these-notes][About these notes]]
  - [[#basic-design][Basic design]]
    - [[#zmq-ports-bidirectional-tcp-connections][ZMQ, Ports, bidirectional TCP connections]]
      - [[#we-use-zmq-for-ipc][We use ZMQ for IPC]]
      - [[#port-dedicated-using--dealerrouter-in-zmq4-deprecated][Port Dedicated, using  Dealer/Router in ZMQ4 (deprecated)]]
      - [[#basic-flow][Basic Flow]]
      - [[#unique-itentifiers----ulids][Unique Itentifiers -- ULIDs]]
      - [[#errors-with-zmq4][Errors with ZMQ4]]
  - [[#sequence-numbers-and-innovation-numbers][Sequence Numbers and Innovation Numbers]]
  - [[#miscellaneous][Miscellaneous]]
  - [[#hebbian-learning][Hebbian Learning]]
  - [[#spiking][Spiking]]
    - [[#neuron-per-spike][Neuron per spike]]
  - [[#generic-floats][Generic Floats]]
  - [[#issues-with-compiles-and-builds][Issues with compiles and builds]]
    - [[#you-must-add-to-exposed-modules][You must add to exposed-modules]]
    - [[#llvm-general-building][LLVM-general building]]
  - [[#we-now-have-first-critter][We now have First Critter]]
    - [[#evaluation][Evaluation]]
      - [[#using-zeromq4-haskell][Using ZeroMQ4-haskell]]
      - [[#design-of-interplay-between-the-data-sources-training-and-data-sinks-with-0mq][Design of interplay between the data sources, training, and data sinks with 0mq]]
    - [[#critters][Critters]]
      - [[#persistence][persistence]]
      - [[#modadic-critters][Modadic Critters?]]
    - [[#spiking-1][Spiking]]
    - [[#theory-of-critters][Theory of Critters]]
    - [[#using-type-classes-and-type-families-to-handle-different-sigmoids][Using type classes and type families to handle different sigmoids]]
    - [[#neurons-and-a-spatial-temporal-indexing][Neurons and a spatial-temporal indexing]]
    - [[#dataworkflow-between-ss-and-the-systems-that-will-be-learned][Data/Workflow between SS and the systems that will be learned]]
  - [[#trial-problem-to-train-on][Trial problem to train on]]
    - [[#crypto-market-feeds][Crypto market feeds]]
  - [[#gotchas-and-deleted-code-snippets][Gotchas and Deleted Code Snippets]]
  - [[#unagi-chan][Unagi Chan]]

** About these notes
   These notes are basically meant for only me. I make no
   promises that they will be up-to-date or even meaningful to anyone
   but myself. For the authorative docs, see the README.org. You may find
   some utility here as these notes may represent a history of
   various design decisions I've made to create Spiking NEAT, but as I said,
   no promises.
** Basic design
   + We shall have, instead of negative weights,
     negative or inhibitory neurons, which will send
     the weights as negative to the neuros its conneted
     to.
   + Instead of averaging, we will use spikes. There
     are the time instants, and for each time instant
     the inputs (and their weights) for each neuron
     will be tallied, and if it reaches firing
     threshold, said neuron will fire its own pulse.
   + Some neurons will continually fire pulses at
     regular intervals. This will serve as a bias.

     I actually think there should be a number of bias
     neurons firing at regular intervals. The firing
     rates should not necessairily be random,
     either. Maybe Fibonancii? Maybe these rates
     themselves should be evolved?
   + In the Stanley algorithm, the neurons and genes
     are indexed by integers. To promote efficient
     execution of these neurons, should we maintain
     that? Perhaps we should simply create the IR from
     the indicies directly.
*** ZMQ, Ports, bidirectional TCP connections
**** We use ZMQ for IPC
      since it is supported for nearly all languages that are in
      popular or semi-popular use.
**** Port Dedicated, using  Dealer/Router in ZMQ4 (deprecated)
      All Dealer clients must present a unique identifer when
      they connect. All connections shall be bidirectional.
      + The messae Payloads shall define the protocols they may use.
      + Since we are using the Dealer-Router
        configuration, no need to have lots of ports
        anymore. We may need a seperate port per
        dealer, but even that is not entirely clear.
**** Basic Flow
      See README.org's Interfacing with Spiking NEAT
**** Unique Itentifiers -- ULIDs
      We have elected to use ULIDs, since they are
      monontonic.  The default implementations have
      resolutions only down to the millisecond. Which
      is fine for a single server. We will not deal
      with multiple distributed severs at this time.
**** Errors with ZMQ4
      Assertion failed: !_current_out (/usr/src/debug/zeromq/zeromq/src/router.cpp:166)
      fish: Job 1, 'cabal run playground-zmq-router' terminated by signal SIGABRT (Abort)
      + If I have to clone ZMQ4 and fix this problem myself, I will.
      
** Sequence Numbers and Innovation Numbers
   Innovation numbers are used to trace this history of
   evolution.  They are not intended to be IDs.

** Miscellaneous
   + I had to remove Node and Connection from Gene
     and make them separate. Haskell doesnät like to
     array the type constructor otherwise.
** Hebbian Learning
   I need to explore the inclusion of Hebbian leaarning for S-NEAT.
   + w ij ←w ij +η⋅r i ⋅r j -- just look up the actual formula.
   + How will this work in the spiking context? Do I allow the
     weights to change as the critter is working, as opposed to only
     doing that during evolution?
   + Do I Lamackian those changes back to the genes?
** Spiking
   I have not understood how I shall exactly implement
   spiking. Do I evaluate the entire critter per spike?
   Or do I evaluate each neuron per spike?
   + Whole critter eval
     This would entail pushing out all the evaluations
     to the output neurons per spike, and during that
     spike allowing for settlement due to loops in neurons.
   + Per Spike Evaluation
     This would be slower, but a bit closer to the
     actual biological context. But a lot more compute
     intensive, meaning more parallel computation perhaps.
   + I am leaning toward the latter. Neuron per spike. We will
     have to optimize for speed later.
*** Neuron per spike
    A vector of neurons -- or nodes -- will have to be
    maintained somewhere, and I was thinking floats. But what
    if we used Complex numbers or even quaternions instead?

    I will need to make it all generic, which Haskell
    will allow me to do easily enough.
** Generic Floats
   I am calling them that for now,
   but really I want to be able to
   use complex numbers or even quaturnions
   instead. I do not know where this
   will lead. It may make it able to
   latch on to deeper nuances of learning.
   
** Issues with compiles and builds
*** You must add to exposed-modules
    everything in your library that might be used by
    main. Just throw everything in or you may see linker errors
*** LLVM-general building
    src/LLVM/General/Prelude.hs:9:5: error: [GHC-69158]
    Conflicting exports for ‘unzip’:
    ‘module Prelude’ exports ‘Prelude.unzip’
    imported from ‘Prelude’ at src/LLVM/General/Prelude.hs:(16,1)-(25,3)
    (and originally defined in ‘ghc-internal-9.1001.0:GHC.Internal.List’)
    ‘module Data.Functor’ exports ‘Data.Functor.unzip’
    imported from ‘Data.Functor’ at src/LLVM/General/Prelude.hs:29:1-19
    (and originally defined in ‘ghc-internal-9.1001.0:GHC.Internal.Data.Functor’)
    |   |
      9 |     module Data.Functor,
            | ^^^^^^^^^^^^^^^^^^^ |
    + said problems ameroliated
** We now have First Critter
*** Evaluation
    We have decided to go in "whole hog" and 
    implement the input from the external world, reshape the
    signals, and feed it to the input of the critter, do the evaluation,
    and deal with the output. Then we will do the evolution part.
    + The spiking logic will be fully embraced.
    + Signal shaping, vis a vis HTM approaches
    + Spike generator
**** Using ZeroMQ4-haskell
     Let's see how this works out. There's bindings for
     many languages. Other options are not as uptopdate.
     + cabal run playground-zmq-pub -- tcp://127.0.0.1:6666 eltoro
     + cabal run playground-zmq-sub -- tcp://127.0.0.1:6666
     + cereal for CBOR serialization / desealization
**** Design of interplay between the data sources, training, and data sinks with 0mq
     + Data sources will have 2 modes -- training and inference. The inference
        mode will obviously rely on previously trainedd TWEANNs.
     + Evaluation takes place on a seperately-running eval program across
        the zeromq connection. Should this be synchronous or async?
     + I envvision a continuous "training" even if the data source is inference
        mode. 
*** Critters
**** persistence
     We must be able to serialize and deserialze critter populations.
**** Modadic Critters?
     A way to store transitory states of the neurons.
*** Spiking
    How will the spiking work? Neurons will vary between 0 and 1, and will climb as
    the input is still present, and drop off after the input is gone. The inhibitory
    neurons will kick in strong after a neuron fires to inhibit surrounding neurons.
    + Since the neuron strengths will be dropping off quickly, there must be some
      way to gate the optimal time to read out the results.
    + There needs to be an interval driver. I am thinking that the ideal
      would be to genenerate 1000 intervals per second, meaning each would only be
      1 ms long. If processing times increase, it may stretch out. If quick, the
      processisng times will be shorter. I am thinking of keeping them to 1 ms, even
      though it will slow down prcoessing for some instances.
    + Obviously said processing across many Critters must be carried out in parallell.
*** Theory of Critters
    + IVec -- input vector from "the world"
    + OVec -- output vector to "the world"
    + evalcrit :: IVec a -> Critter -> OVec a
                  except there are side effects in the Critter
*** Using type classes and type families to handle different sigmoids
    We can make the handling of the various sigmoid lambdas cleaner
    than it is now.
    
*** Neurons and a spatial-temporal indexing
    Neurons can hava a spatial and temporal (or both) indexing,
    allowing for Hebbian behavior solely based on proximal locality
    shifting the probabilities of wiring together via the guassian.
    + How will this work for a temporal index?
      We will have to figure this out. My initial guess is to 
      have time encoding in the imput data. The temporal index for
      the neurons will be cyclic, and the cycle may vary as well. 
    + Firing porbabilities based on cycling
      We can shift activation levels based on cycling, and have
      different cycles for different neurons.
    + Instead of bias neurons, rhythm neurons.
*** Data/Workflow between SS and the systems that will be learned
    + Flumen Agents -- streaming data input to SS 
** Trial problem to train on
*** Crypto market feeds
    + We need to complete the BiBit feed to use to
      set up our first problem. It is idea because, well,
      this is one of the first things I want to do anyway.
      + The technical analysis should emcompass the history.
        all we need to do is to send the klines, the volume,
        and the Bollinger numbers, SMA, etc.
      + For training, we do historical or live, and do the
        actual evaluation in the short future to see how
        the criters respond.
      + Realtime evolution shall be used as well as spiking.
      + The flow is streaming input, streaming output from the
        many critters, and during training, the critiers are ranked, the ranks
        are sent back to SNeat for evolution.
      + If no criter ranks are sent back, no evolution will take
        place. The critier evaluations can be listened for. We do
        not even need to send the evaluation vectors back all the time,
        but we actually should to avoid unwanted biasing.
      + The evals should be sent back as Maybes.
      + Thusly:
        | StreamingFeed | Crit Ensemble      | Critt Out vectors | Eval   | Evolution |
        |---------------+--------------------+-------------------+--------+-----------|
        | Klines        | Input All Critters | Out Matrix        | Vector | Mate&Mut  |
        | Volumes       |                    |                   |        |           |
        | Technicals    |                    |                   |        |           |
        
** Gotchas and Deleted Code Snippets
  + We cannot do this globally in the cabal file. Has to be file-by-Haskell-file.
    #BEGIN_SRC Cabal
      default-extensions: OverloadedStrings -- blows up SSMonad
                        , GADTs
                        , DeriveGeneric
                        , DeriveAnyClass
    #END_SRC
  + Zio.hs
       #BEGIN_SRC Haskell
           cfg <- getConfig
           return _
           where
             deserPayload ::  forall a2. (Serialize a2) => ByteString -> Either String (Payload a2)
             deserPayload = decode
          
          import Data.Serialize
          import Data.ByteString (ByteString)
          import qualified Data.ByteString.Char8 as BS
          import GHC.Generics (Generic)
          
          data MyData = MyData Int String deriving (Show, Generic)
          
          instance Serialize MyData
          
          serializeList :: [MyData] -> ByteString
          serializeList = encode
          
          deserializeList :: ByteString -> Either String [MyData]
          deserializeList = decode
          
          main :: IO ()
          main = do
              let myList = [MyData 1 "Hello", MyData 2 "World"]
              let serialized = serializeList myList
              putStrLn $ "Serialized data: " ++ BS.unpack serialized
              
              case deserializeList serialized of
                  Left err -> putStrLn $ "Error during deserialization: " ++ err
                   Right deserialized -> putStrLn $ "Deserialized data: " ++ show deserialized
       #END_SRC
** Unagi Chan
  + 2 channels. One for the send and one for the response.
  + multiple threads to handle both the output and input
  + On both sides, the dealers and the router
  + Low-level BSPayload, serialized Payload objects
  + Payload constructurs form the protocols. 
       
   
