cabal-version: 3.16
name:          rhayader
version:       0.0.0.0
synopsis:      A collection of composable Machine Learning engines such as Spiking NEAT, HTM, etc.
description:   Influenced by NEAT, HTM, and Active Inference.
license:       MIT
license-file:  LICENSE
author:        Fred Mitchell
maintainer:    eltoro@atomlogik.de
copyright:     2024 Fred Mitchell & Atomlogik.de
category:      Machine Learning
build-type:    Simple
extra-doc-files: CHANGELOG.org

common commons
    ghc-options:     -O2 -Wall -threaded
    build-depends:
        base >=4.7 && <5
      , pretty-simple
      , random
      , ghc
      , ghc-paths
      , ghc-prim
      , zeromq4-haskell
      , lens
      , bytestring
      , cereal
      , cborg-json
      , haskell-gi
      , async
      , stm
      , stm-chans
      , stm-containers
      , containers
      , text
      , ulid
      , wide-word
      , liquidhaskell
      , liquidhaskell-boot
      , liquid-prelude
      , unagi-chan
      , conduit
    default-language: GHC2024
    default-extensions:
        OverloadedRecordDot
      , DuplicateRecordFields

common bincoms
    build-depends:
        mtl
      , liquidhaskell-boot
      , rhayader

library
    import: commons
    exposed-modules:
        Engine.NEAT
      , SSMonad
      , SSNumeric
      , Engine.AI
      , Engine.Combinators
      , Engine.NEAT.Evolution.Goals
      , Engine.NEAT.Evolution.GoalTypes
      , Engine.NEAT.Genetics.Critters
      , Engine.NEAT.Genetics.Genes
      , Engine.NEAT.Genetics.GeneTypes
      , Engine.NEAT.Genetics.Neurons
      , Engine.NEAT.Population
      , Data.Stream.Zio
      , Data.Stream.Zio.Common
      , Data.Stream.Zio.Dealer
      , Data.Stream.Zio.Router
    other-modules:
        Paths_rhayader
    hs-source-dirs:  lib
    build-depends:
        mtl
      , unordered-containers
      , hashable
      , data-default
      , transformers

executable sneat
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     SNeat.hs
    hs-source-dirs: app

executable flumen
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     Flumen.hs
    hs-source-dirs: app

executable playground-combinators
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     Combinators.hs
    hs-source-dirs: playground

executable playground-dsl
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     CritterDSL.hs
    hs-source-dirs: playground

executable playground-random
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     RandomGen.hs
    hs-source-dirs: playground

executable playground-zmq-pub
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     Prompt.hs
    hs-source-dirs: playground/zmq

executable playground-zmq-sub
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     Display.hs
    hs-source-dirs: playground/zmq

executable playground-zmq-router
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     ZRouter.hs
    hs-source-dirs: playground/zmq

executable playground-zmq-dealer
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     ZDealer.hs
    hs-source-dirs: playground/zmq

executable playground-zmq-bi-ser
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     PairServer.hs
    hs-source-dirs: playground/zmq

executable playground-zmq-bi-cli
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     PairClient.hs
    hs-source-dirs: playground/zmq

executable playground-unagi
    import:      commons, bincoms
    ghc-options: -rtsopts -with-rtsopts=-N
    main-is:     Unagi.hs
    hs-source-dirs: playground

test-suite ss-spec
    import:      commons, bincoms
    type:        exitcode-stdio-1.0
    main-is:     Spec.hs
    hs-source-dirs: test
    build-depends:
        hspec
      , QuickCheck
