cabal-version:      3.14
name:               spiking-neat

version:            0.1.0.0

synopsis:
  Implementation of Spiking Neural Evolution of Augmenting Topologies

description:
  Influenced by NEAT and HTM.

license:            MIT
license-file:       LICENSE
author:             Fred Mitchell
maintainer:         eltoro@atomlogik.de

copyright:          2024 Fred Mitchell & Atomlogik.de
category:           Machine Learning
build-type:         Simple
extra-doc-files:    CHANGELOG.org

common commons
    ghc-options: -O2
                 -Wall
                 -threaded
    build-depends:
        base >=4.7 && <5
      -- , llvm-general >= 3.8 && < 4.0
      , pretty-simple
      , random
      , ghc
      , ghc-paths
      , ghc-prim
      , zeromq4-haskell
      , lens
      , bytestring
      , cereal
      , cborg-json
      , haskell-gi
      , async
      , stm
      , stm-chans
      , stm-containers
      , containers
      , text
      , ulid
      , wide-word
      , liquidhaskell
      , liquidhaskell-boot
      , liquid-prelude
      , unagi-chan
    default-language: GHC2024
    default-extensions: OverloadedRecordDot 
                      , DuplicateRecordFields

common bincoms
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
                                 
library
    import:           commons
    exposed-modules:
        NEAT
      , SSMonad
      , SSNumeric
      , Evolution.Goals
      , Evolution.GoalTypes
      , Genetics.Critters
      , Genetics.Genes
      , Genetics.GeneTypes
      , Genetics.Neurons
      , Population.Population
      , Data.Stream.Zio
      , Data.Stream.Zio.Common
      , Data.Stream.Zio.Dealer
      , Data.Stream.Zio.Router
    other-modules:
        Paths_spiking_neat
    hs-source-dirs:
        lib
    build-depends:
        mtl
      , unordered-containers
      , hashable
      , data-default
      , transformers
      -- , plugins

executable sneat
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     SNeat.hs
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
    hs-source-dirs:   app

executable flumen
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     Flumen.hs
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
    hs-source-dirs:   app

executable playground-dsl
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     CritterDSL.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground

executable playground-random
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     RandomGen.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground

executable playground-zmq-pub
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     Prompt.hs
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-zmq-sub
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     Display.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-zmq-router
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     ZRouter.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-zmq-dealer
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     ZDealer.hs
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-zmq-bi-ser
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     PairServer.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-zmq-bi-cli
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     PairClient.hs
    build-depends:
        mtl
      , liquidhaskell-boot
      , spiking-neat
    hs-source-dirs:
        playground/zmq

executable playground-unagi
    import:           commons
                    , bincoms
    ghc-options: -rtsopts
                 -with-rtsopts=-N
    main-is:     Unagi.hs
    build-depends:
        mtl
      , spiking-neat
    hs-source-dirs:
        playground

test-suite ss-spec
    import:           commons
                    , bincoms
    type: exitcode-stdio-1.0
    main-is: Spec.hs
    hs-source-dirs: test
    build-depends:
        base >=4.7 && <5
      , hspec
      , QuickCheck
      , spiking-neat
